### ISSUE TITLE
missing function error Serial.printf() in example simple

### ISSUE THREAD

**Issue by zzts** [joba-1/Joba_Tsl2561#2]
compile fails with an error ‘class CDCSerialClass’ has no member named ‘printf’.  The Serial library does not implement printf().

**Comment by joba-1** [comment]
So, the core libs for your chip dont support printf. Interesting. I developed this for esp8266. Which chip are you using? Can you give me a link where I can download the core libs of it, to have a look what it actually supports? 

Anyways, I use printf only in the examples. The lib itself should be fine for your own code.

**Comment by zzts** [comment]
arduinon 101/curie on an Udoo x64 ultra.  According to the Arduino reference page https://www.arduino.cc/reference/en/language/functions/communication/serial/ none of the core libraries include it.  Only print and println.

**Comment by joba-1** [comment]
I‘ll adapt the examples. Shouldn‘t take long...

**Comment by joba-1** [comment]
I just released V2.0.2. This should fix the issue
