### ISSUE TITLE
FW: Some bugs in using Wire library

### ISSUE THREAD

**Issue by reloxx13** [joba-1/Joba_Tsl2561#3]
Heya,

someone found some usage bugs of the wire library

> File "Sonoff-Tasmota/lib/Joba_Tsl2561/src/Tsl2561.cpp", the "readByte()" and "readWord()" have extra Wire.endTranmission() in the return.

Credits @Koepel
https://github.com/arendst/Sonoff-Tasmota/issues/2442

**Comment by joba-1** [comment]
Thanks for the hint.
It seems reasonable to drop the extra endTransmission()s.
I will adapt the code after some testing, especially with the esp8266 Wire variant.

**Comment by joba-1** [comment]
opened #4, rfc :)

**Comment by joba-1** [comment]
fixed with merged #4 (v2.0.6)
